#include "Webhook.hpp";
#include "Settings.hpp";
#include "LevelInfo.hpp";


std::string url = Settings::defaultWebhook();
std::string username = Settings::displayName();


web::WebTask Webhook::sendDeath(GJGameLevel* currentLevel, int deathPct) {
    // now, the function is called "send death"
    // but it also sends completions

	web::WebRequest req = web::WebRequest();

	auto levelName = currentLevel->m_levelName;
	auto creatorName = currentLevel->m_creatorName;
    auto thumbnail = LevelInfo::getDifficultyImage(LevelInfo::getLevelDifficulty(currentLevel));

	log::debug("Sending POST request to {}", url);

    // yeees
    std::ostringstream rawJson;
    if (deathPct < 100) {
        rawJson << R"({
        "username": ")" << username << R"(",
        "embeds": [
            {
                "author": {
                    "name": "Getting Far"
                },
                "title": "**)" << username << R"(** just died at )" << deathPct
            << R"(% on **)" << levelName << R"( by )" << creatorName << R"(**",
                "description": "*This message was generated by cluckwork's Getting Far Mod*",
                "thumbnail": {
                    "url": ")" << thumbnail << R"("
                }
            }
        ]
    })";
    }
    else {
        // they win
        rawJson << R"({
        "username": ")" << username << R"(",
        "embeds": [
            {
                "author": {
                    "name": "Getting Far"
                },
                "title": "**)" << username << R"(** just completed **)" 
                 << levelName << R"( by )" << creatorName << R"(**",
                "description": "*This message was generated by cluckwork's Getting Far Mod*",
                "thumbnail": {
                    "url": ")" << thumbnail << R"("
                }
            }
        ]
    })";
    }

    // todo handle exception if json is invalid

    req.bodyJSON(matjson::parse(rawJson.str()).unwrap());

	req.header("Content-Type", "application/json");

	return req.post(url);
}
